runtime: python27
api_version: 1
threadsafe: true
service: timetracker

# [START handlers]
handlers:
- url: /_ah/spi/.*
  script: timetracker.application
  secure: always

- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /bootstrap
  static_dir: bootstrap
# [END handlers]

# [START libraries]
libraries:
- name: endpoints
  version: "1.0"
- name: jinja2
  version: latest
- name: webapp2
  version: latest

# [END libraries]
