runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /_ah/spi/.*
  script: timetracker.application
  secure: always

- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: ../dist/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
# [END handlers]

# [START libraries]
libraries:
- name: endpoints
  version: "1.0"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
